// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using infra.Data;

#nullable disable

namespace infra.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("domain.Entities.ApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AllowedIpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("RequestCount")
                        .HasColumnType("bigint");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeactivationReason")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FirstName");

                    b.HasIndex("IsActive");

                    b.HasIndex("LastLoginAt");

                    b.HasIndex("LastName");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("FirstName", "LastName");

                    b.HasIndex("IsActive", "CreatedAt");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("domain.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("RevocationReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("domain.Entities.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId", "SessionId")
                        .IsUnique();

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("domain.Entities.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Summary")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecasts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Summary = "Cool"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Summary = "Mild"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Summary = "Warm"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Summary = "Hot"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Summary = "Balmy"
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2025, 10, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Summary = "Mild"
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Summary = "Cool"
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2025, 10, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Summary = "Chilly"
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2025, 10, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Summary = "Bracing"
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2025, 10, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Summary = "Cool"
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Summary = "Mild"
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2025, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Summary = "Warm"
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Summary = "Balmy"
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Summary = "Hot"
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Summary = "Sweltering"
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateTime(2025, 11, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Summary = "Hot"
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateTime(2025, 11, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Summary = "Warm"
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Summary = "Mild"
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateTime(2025, 11, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Summary = "Cool"
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Summary = "Chilly"
                        },
                        new
                        {
                            Id = 21,
                            Date = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Summary = "Freezing"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("domain.Entities.ApiKey", b =>
                {
                    b.HasOne("domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("domain.ValueObjects.ApiKeyScopes", "Scopes", b1 =>
                        {
                            b1.Property<int>("ApiKeyId")
                                .HasColumnType("integer");

                            b1.Property<string>("_scopesString")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Scopes");

                            b1.HasKey("ApiKeyId");

                            b1.ToTable("ApiKeys");

                            b1.WithOwner()
                                .HasForeignKey("ApiKeyId");
                        });

                    b.Navigation("Scopes")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("domain.Entities.UserSession", b =>
                {
                    b.HasOne("domain.Entities.Session", "Session")
                        .WithMany("UserSessions")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("domain.Entities.ApplicationUser", "User")
                        .WithMany("UserSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("domain.Entities.WeatherForecast", b =>
                {
                    b.OwnsOne("domain.ValueObjects.Temperature", "Temperature", b1 =>
                        {
                            b1.Property<int>("WeatherForecastId")
                                .HasColumnType("integer");

                            b1.Property<int>("Celsius")
                                .HasColumnType("integer")
                                .HasColumnName("TemperatureC");

                            b1.HasKey("WeatherForecastId");

                            b1.ToTable("WeatherForecasts");

                            b1.WithOwner()
                                .HasForeignKey("WeatherForecastId");

                            b1.HasData(
                                new
                                {
                                    WeatherForecastId = 1,
                                    Celsius = 15
                                },
                                new
                                {
                                    WeatherForecastId = 2,
                                    Celsius = 18
                                },
                                new
                                {
                                    WeatherForecastId = 3,
                                    Celsius = 22
                                },
                                new
                                {
                                    WeatherForecastId = 4,
                                    Celsius = 28
                                },
                                new
                                {
                                    WeatherForecastId = 5,
                                    Celsius = 25
                                },
                                new
                                {
                                    WeatherForecastId = 6,
                                    Celsius = 20
                                },
                                new
                                {
                                    WeatherForecastId = 7,
                                    Celsius = 16
                                },
                                new
                                {
                                    WeatherForecastId = 8,
                                    Celsius = 12
                                },
                                new
                                {
                                    WeatherForecastId = 9,
                                    Celsius = 8
                                },
                                new
                                {
                                    WeatherForecastId = 10,
                                    Celsius = 14
                                },
                                new
                                {
                                    WeatherForecastId = 11,
                                    Celsius = 19
                                },
                                new
                                {
                                    WeatherForecastId = 12,
                                    Celsius = 23
                                },
                                new
                                {
                                    WeatherForecastId = 13,
                                    Celsius = 26
                                },
                                new
                                {
                                    WeatherForecastId = 14,
                                    Celsius = 30
                                },
                                new
                                {
                                    WeatherForecastId = 15,
                                    Celsius = 35
                                },
                                new
                                {
                                    WeatherForecastId = 16,
                                    Celsius = 32
                                },
                                new
                                {
                                    WeatherForecastId = 17,
                                    Celsius = 27
                                },
                                new
                                {
                                    WeatherForecastId = 18,
                                    Celsius = 21
                                },
                                new
                                {
                                    WeatherForecastId = 19,
                                    Celsius = 17
                                },
                                new
                                {
                                    WeatherForecastId = 20,
                                    Celsius = 10
                                },
                                new
                                {
                                    WeatherForecastId = 21,
                                    Celsius = 2
                                });
                        });

                    b.Navigation("Temperature")
                        .IsRequired();
                });

            modelBuilder.Entity("domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("UserSessions");
                });

            modelBuilder.Entity("domain.Entities.Session", b =>
                {
                    b.Navigation("UserSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
